WebGestionPlanilla/Controllers/AreaController.cs
using GP.Entities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;

namespace WebGestionPlanilla.Controllers
{
    public class AreaController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetArea(Area obj)
        {
            var ctx = HttpContext.GetOwinContext();
            var tipoUsuario = ctx.Authentication.User.Claims.FirstOrDefault().Value;
            obj.Auditoria = new Auditoria
            {
                TipoUsuario = tipoUsuario
            };

            string draw = Request.Form.GetValues("draw")[0];
            int inicio = Convert.ToInt32(Request.Form.GetValues("start").FirstOrDefault());
            int fin = Convert.ToInt32(Request.Form.GetValues("length").FirstOrDefault());

            obj.Operacion = new Operacion
            {
                Inicio = (inicio / fin),
                Fin = fin
            };

            var bussingLogic = new GP.BusinessLogic.BLArea();
            var response = bussingLogic.GetArea(obj);

            var Datos = response.Data;
            int totalRecords = Datos.Any() ? Datos.FirstOrDefault().Operacion.TotalRows : 0;
            int recFilter = totalRecords;

            var result = (new
            {
                draw = Convert.ToInt32(draw),
                recordsTotal = totalRecords,
                recordsFiltered = recFilter,
                data = Datos
            });

            return Json(result);
        }

        public JsonResult InsertUpdateArea(Area obj)
        {
            var bussingLogic = new GP.BusinessLogic.BLArea();
            var response = bussingLogic.InsertUpdateArea(obj);

            return Json(response);
        }

        public JsonResult DeleteArea(Area obj)
        {
            var bussingLogic = new GP.BusinessLogic.BLArea();
            var response = bussingLogic.DeleteArea(obj);

            return Json(response);
        }

    }
}

WebGestionPlanilla/Controllers/CargoController.cs
using GP.Entities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;

namespace WebGestionPlanilla.Controllers
{
    public class CargoController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetCargo(Cargo obj)
        {
            var ctx = HttpContext.GetOwinContext();
            var tipoUsuario = ctx.Authentication.User.Claims.FirstOrDefault().Value;
            obj.Auditoria = new Auditoria
            {
                TipoUsuario = tipoUsuario
            };

            string draw = Request.Form.GetValues("draw")[0];
            int inicio = Convert.ToInt32(Request.Form.GetValues("start").FirstOrDefault());
            int fin = Convert.ToInt32(Request.Form.GetValues("length").FirstOrDefault());

            obj.Operacion = new Operacion
            {
                Inicio = (inicio / fin),
                Fin = fin
            };

            var bussingLogic = new GP.BusinessLogic.BLCargo();
            var response = bussingLogic.GetCargo(obj);

            var Datos = response.Data;
            int totalRecords = Datos.Any() ? Datos.FirstOrDefault().Operacion.TotalRows : 0;
            int recFilter = totalRecords;

            var result = (new
            {
                draw = Convert.ToInt32(draw),
                recordsTotal = totalRecords,
                recordsFiltered = recFilter,
                data = Datos
            });

            return Json(result);
        }

        public JsonResult InsertUpdateCargo(Cargo obj)
        {
            var bussingLogic = new GP.BusinessLogic.BLCargo();
            var response = bussingLogic.InsertUpdateCargo(obj);

            return Json(response);
        }

        public JsonResult DeleteCargo(Cargo obj)
        {
            var bussingLogic = new GP.BusinessLogic.BLCargo();
            var response = bussingLogic.DeleteCargo(obj);

            return Json(response);
        }

    }
}

WebGestionPlanilla/Controllers/ReporteController.cs
using NPOI.HSSF.Util;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebGestionPlanilla.Controllers
{
    public class ReporteController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public void GenerarReporteTurno(string Periodo)
        {
            var NombreExcel = "Reporte Turno";

            // Recuperamos la data  de las consulta DB
            var bussingLogic = new GP.BusinessLogic.BLReporte();
            var data = bussingLogic.GetReporteTurno(Periodo);

            string[] Cabezeras = {
                    "Nombre y Apellido", "Turno", "Asistencia", "Tardanzas", "Faltas"
            };

            // Creación del libro excel xlsx.
            var wb = new XSSFWorkbook();

            // Creación del la hoja y se especifica un nombre
            ISheet sheet = wb.CreateSheet(NombreExcel);

            // Contadores para filas y columnas.
            int rownum = 0;
            int cellnum = 0;

            // Creacion del estilo de la letra para las cabeceras.
            var fontCab = wb.CreateFont();
            fontCab.FontHeightInPoints = 12;
            fontCab.FontName = "Calibri";
            fontCab.Color = HSSFColor.White.Index;

            // Creacion del color del estilo.
            var colorCab = new XSSFColor(new byte[] { 7, 105, 173 });

            // Se crea el estilo y se agrega el font al estilo
            var styleCab = (XSSFCellStyle)wb.CreateCellStyle();
            styleCab.SetFont(fontCab);
            styleCab.FillForegroundXSSFColor = colorCab;
            styleCab.FillPattern = FillPattern.SolidForeground;

            // Se crea la primera fila para las cabceras.
            IRow row = sheet.CreateRow(rownum++);
            ICell cell;

            foreach (var item in Cabezeras)
            {
                // Se crea celdas y se agrega las cabeceras
                cell = row.CreateCell(cellnum++);
                cell.SetCellValue(item);
                cell.CellStyle = styleCab;

                sheet.AutoSizeColumn(cellnum);
            }

            // Creacion del estilo de la letra para la data.
            var fontBody = wb.CreateFont();
            fontBody.FontHeightInPoints = 12;
            fontBody.FontName = "Arial";

            var styleBody = (XSSFCellStyle)wb.CreateCellStyle();
            styleBody.SetFont(fontBody);


            // Impresión de la data
            foreach (var item in data.Data)
            {
                cellnum = 0;
                row = sheet.CreateRow(rownum++);

                sheet.AutoSizeColumn(cellnum);
                AddValue(row, cellnum++, item.Nombres.ToString(), styleBody, sheet);
                AddValue(row, cellnum++, item.Turno.Descripcion.ToString(), styleBody, sheet);
                AddValue(row, cellnum++, item.HorasTrabajadas.DiasTrabajados.ToString(), styleBody, sheet);
                AddValue(row, cellnum++, item.HorasTrabajadas.DiasTardanzas.ToString(), styleBody, sheet);
                AddValue(row, cellnum++, item.HorasTrabajadas.DiasNoTrabajados.ToString(), styleBody, sheet);
            }


            var nameFile = NombreExcel + "_" + DateTime.Now.ToString("dd_MM_yyyy HH:mm:ss") + ".xlsx";
            Response.AddHeader("content-disposition", "attachment; filename=" + nameFile);
            Response.ContentType = "application/octet-stream";
            Stream outStream = Response.OutputStream;
            wb.Write(outStream);
            outStream.Close();
            Response.End();
        }

        public void GenerarReporteArea(string Periodo)
        {
            var NombreExcel = "Reporte Area";

            // Recuperamos la data  de las consulta DB
            var bussingLogic = new GP.BusinessLogic.BLReporte();
            var data = bussingLogic.GetReporteArea(Periodo);

            string[] Cabezeras = {
                    "Nombre y Apellido", "Area", "Cargo", "Asistencia", "Tardanzas", "Faltas", "Asistencia Area", "Tardanzas Area", "Faltas Area"
            };

            // Creación del libro excel xlsx.
            var wb = new XSSFWorkbook();

            // Creación del la hoja y se especifica un nombre
            ISheet sheet = wb.CreateSheet(NombreExcel);

            // Contadores para filas y columnas.
            int rownum = 0;
            int cellnum = 0;

            // Creacion del estilo de la letra para las cabeceras.
            var fontCab = wb.CreateFont();
            fontCab.FontHeightInPoints = 12;
            fontCab.FontName = "Calibri";
            fontCab.Color = HSSFColor.White.Index;

            // Creacion del color del estilo.
            var colorCab = new XSSFColor(new byte[] { 7, 105, 173 });

            // Se crea el estilo y se agrega el font al estilo
            var styleCab = (XSSFCellStyle)wb.CreateCellStyle();
            styleCab.SetFont(fontCab);
            styleCab.FillForegroundXSSFColor = colorCab;
            styleCab.FillPattern = FillPattern.SolidForeground;

            // Se crea la primera fila para las cabceras.
            IRow row = sheet.CreateRow(rownum++);
            ICell cell;

            foreach (var item in Cabezeras)
            {
                // Se crea celdas y se agrega las cabeceras
                cell = row.CreateCell(cellnum++);
                cell.SetCellValue(item);
                cell.CellStyle = styleCab;

                sheet.AutoSizeColumn(cellnum);
            }

            // Creacion del estilo de la letra para la data.
            var fontBody = wb.CreateFont();
            fontBody.FontHeightInPoints = 12;
            fontBody.FontName = "Arial";

            var styleBody = (XSSFCellStyle)wb.CreateCellStyle();
            styleBody.SetFont(fontBody);


            // Impresión de la data
            foreach (var item in data.Data)
            {
                cellnum = 0;
                row = sheet.CreateRow(rownum++);

                sheet.AutoSizeColumn(cellnum);
                AddValue(row, cellnum++, item.Nombres.ToString(), styleBody, sheet);
                AddValue(row, cellnum++, item.Area.Descripcion.ToString(), styleBody, sheet);
                AddValue(row, cellnum++, item.Cargo.Descripcion.ToString(), styleBody, sheet);
                AddValue(row, cellnum++, item.HorasTrabajadas.DiasTrabajados.ToString(), styleBody, sheet);
                AddValue(row, cellnum++, item.HorasTrabajadas.DiasTardanzas.ToString(), styleBody, sheet);
                AddValue(row, cellnum++, item.HorasTrabajadas.DiasNoTrabajados.ToString(), styleBody, sheet);
                AddValue(row, cellnum++, item.Area.Asistencias.ToString(), styleBody, sheet);
                AddValue(row, cellnum++, item.Area.Tardanzas.ToString(), styleBody, sheet);
                AddValue(row, cellnum++, item.Area.Faltas.ToString(), styleBody, sheet);
            }


            var nameFile = NombreExcel + "_" + DateTime.Now.ToString("dd_MM_yyyy HH:mm:ss") + ".xlsx";
            Response.AddHeader("content-disposition", "attachment; filename=" + nameFile);
            Response.ContentType = "application/octet-stream";
            Stream outStream = Response.OutputStream;
            wb.Write(outStream);
            outStream.Close();
            Response.End();
        }

        public void AddValue(IRow row, int cellnum, string value, ICellStyle styleBody, ISheet sheet)
        {
            ICell cell;
            cell = row.CreateCell(cellnum);
            cell.SetCellValue(value);
            cell.CellStyle = styleBody;
            sheet.AutoSizeColumn(cellnum);

        }
    }
}

WebGestionPlanilla/Controllers/TurnoController.cs
using GP.Entities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;

namespace WebGestionPlanilla.Controllers
{
    public class TurnoController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetTurno(Turno obj)
        {
            var ctx = HttpContext.GetOwinContext();
            var tipoUsuario = ctx.Authentication.User.Claims.FirstOrDefault().Value;
            obj.Auditoria = new Auditoria
            {
                TipoUsuario = tipoUsuario
            };

            string draw = Request.Form.GetValues("draw")[0];
            int inicio = Convert.ToInt32(Request.Form.GetValues("start").FirstOrDefault());
            int fin = Convert.ToInt32(Request.Form.GetValues("length").FirstOrDefault());

            obj.Operacion = new Operacion
            {
                Inicio = (inicio / fin),
                Fin = fin
            };

            var bussingLogic = new GP.BusinessLogic.BLTurno();
            var response = bussingLogic.GetTurno(obj);

            var Datos = response.Data;
            int totalRecords = Datos.Any() ? Datos.FirstOrDefault().Operacion.TotalRows : 0;
            int recFilter = totalRecords;

            var result = (new
            {
                draw = Convert.ToInt32(draw),
                recordsTotal = totalRecords,
                recordsFiltered = recFilter,
                data = Datos
            });

            return Json(result);
        }

        public JsonResult InsertUpdateTurno(Turno obj)
        {
            var bussingLogic = new GP.BusinessLogic.BLTurno();
            var response = bussingLogic.InsertUpdateTurno(obj);

            return Json(response);
        }

        public JsonResult DeleteTurno(Turno obj)
        {
            var bussingLogic = new GP.BusinessLogic.BLTurno();
            var response = bussingLogic.DeleteTurno(obj);

            return Json(response);
        }

    }
}

WebGestionPlanilla/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <title>@ViewBag.Title - Sistema de Ventas</title>
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@

    <link href="~/Content/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/lib/jquery-ui/css/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/lib/ionicons/css/ionicons.min.css" rel="stylesheet" />
    <link href="~/Content/lib/dataTables/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/lib/dataTables/css/select.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/lib/select2/css/select2.min.css" rel="stylesheet" />
    <link href="~/Content/lib/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet" />
    <link href="~/Content/lib/adminLTE/css/adminLTE.min.css" rel="stylesheet" />
    <link href="~/Content/css/_all-skins.css" rel="stylesheet" />
    <link href="~/Content/css/main.css" rel="stylesheet" />
    <link href="~/Content/lib/bootstrap-timepicker/css/bootstrap-timepicker.min.css" rel="stylesheet" />

</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="@Url.Action("Index", "Home")" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini">
                    GP
                </span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg">
                    GestionPlanilla
                </span>
            </a>
            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Application Name-->
                <div class="navbar-brand pull-left">
                    <label class="hidden-xs">
                        Inicio
                        <i class="fa fa-angle-right" aria-hidden="true"></i>
                        <small>@ViewBag.Title</small>
                    </label>
                </div>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account Menu -->
                        @{Html.RenderPartial("_LayoutMenuUserAccount");}
                    </ul>
                </div>
            </nav>
        </header>
        @if (User.Identity.IsAuthenticated)
        {
            <aside class="main-sidebar">
                <section class="sidebar" style="height:auto;">
                    <ul class="sidebar-menu" data-widget="tree">
                        <li class="header">MENU PRINCIPAL</li>
                        <li>
                            <a href="@Url.Action("Index", "Home")">
                                <i class="fa fa-th"></i> <span>Inicio</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Marcacion")">
                                <i class="fa fa-fw fa-book"></i> <span>Marcación</span>
                            </a>
                        </li>
                        @if (User.Identity.GetUserId().Equals("1"))
                        {
                            <li>
                                <a href="@Url.Action("Index", "HorasTrabajadas")">
                                    <i class="fa fa-clock-o"></i> <span>Horas Trabajadas</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Vacaciones")">
                                    <i class="fa fa-calendar-check-o"></i> <span>Vacaciones</span>
                                </a>
                            </li>
                            <li class="treeview">
                                <a href="#">
                                    <i class="fa fa-calculator"></i> <span>Calculos</span>
                                    <span class="pull-right-container">
                                        <i class="fa fa-angle-left pull-right"></i>
                                    </span>
                                </a>                                         
                                <ul class="treeview-menu">
                                    <li>
                                        <a href="@Url.Action("Index", "Calculos")">
                                            <i class="fa fa-calculator"></i> <span>Calculos</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index", "TipoCalculos")">
                                            <i class="fa fa-tags"></i> <span>Tipo de calculo</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "BoletaPago")">
                                    <i class="fa fa-file-pdf-o"></i> <span>Boleta de Pago</span>
                                </a>
                            </li>
                            <li class="treeview">
                                <a href="#">
                                    <i class="fa fa-wrench"></i> <span>Mantenimientos</span>
                                    <span class="pull-right-container">
                                        <i class="fa fa-angle-left pull-right"></i>
                                    </span>
                                </a>
                                <ul class="treeview-menu">
                                    <li>
                                        <a href="@Url.Action("Index", "Trabajador")">
                                            <i class="fa fa-user"></i> <span>Trabajador</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index", "Area")">
                                            <i class="fa fa-users"></i> <span>Area</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index", "Cargo")">
                                            <i class="fa fa-briefcase"></i> <span>Cargo</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Index", "Turno")">
                                            <i class="fa fa-hourglass"></i> <span>Turno</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Reporte")">
                                    <i class="fa fa-file-excel-o"></i> <span>Reportes</span>
                                </a>
                            </li>

                        }
                    </ul>
</section>
            </aside>

        }
        else
        {
            <aside class="main-sidebar">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar" style="height:auto;">
                    <!-- Sidebar Menu -->
                    <ul class="sidebar-menu" data-widget="tree">
                        <li class="header">MENU PRINCIPAL</li>
                        <!-- Optionally, you can add icons to the links -->
                    </ul>
                </section>
            </aside>
        }


        <div class="content-wrapper" id="mainContent">
            @RenderBody()
        </div>
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <label>@(string.Format("{0} {1}", "GestionPlanilla", "V1"))</label>
            </div>
            @*<label>@AppConfig.ApplicationCopyright</label>*@
        </footer>
    </div>
    @{ Html.RenderPartial("_LayoutModals"); }

    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)*@
    <script src="~/Content/lib/jquery/js/jquery-3.3.1.min.js"></script>
    <script src="~/Content/lib/jquery/js/jquery.validate.min.js"></script>
    <script src="~/Content/lib/jquery/js/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Content/lib/jquery-ui/js/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Content/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Content/lib/respond/js/respond.min.js"></script>
    <script src="~/Content/lib/select2/js/select2.full.min.js"></script>
    <script src="~/Content/lib/select2/js/es.js"></script>
    <script src="~/Content/lib/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="~/Content/lib/bootstrap-datepicker/js/bootstrap-datepicker.es.min.js"></script>
    <script src="~/Content/lib/dataTables/js/jquery.dataTables.min.js"></script>
    <script src="~/Content/lib/dataTables/js/dataTables.bootstrap.min.js"></script>
    <script src="~/Content/lib/dataTables/js/dataTables.select.min.js"></script>
    <script src="~/Content/lib/fastclick/js/fastclick.js"></script>
    <script src="~/Content/lib/adminLTE/js/adminlte.js"></script>
    <script src="~/Content/lib/dataTables/js/buttons.html5.min.js"></script>
    <script src="~/Content/lib/dataTables/js/dataTables.buttons.min.js"></script>
    <script src="~/Content/lib/dataTables/js/jszip.min.js"></script>
    <script src="~/Content/lib/bootstrap-timepicker/js/bootstrap-timepicker.min.js"></script>
    <script type="text/javascript">
            var baseSiteUrl = '@Url.Content("~/")';
    </script>
    <script src="~/Content/js/app.js"></script>
    @RenderSection("scripts", required: false)

</body>
</html>

WebGestionPlanilla/Views/Shared/_LayoutMenuUserAccount.cshtml
@using Microsoft.AspNet.Identity

@if (User.Identity.IsAuthenticated)
{
    <li class="dropdown user user-menu">
        <!-- Menu Toggle Button -->
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <!-- The user image in the navbar-->
            <img src="~/Content/img/user-256.png" class="user-image" alt="User Image" />
            <!-- hidden-xs hides the username on small devices so only the image appears. -->
            <span class="hidden-xs">@User.Identity.GetUserName().ToUpper()</span>
        </a>
        <ul class="dropdown-menu">
            <!-- The user image in the menu -->
            <li class="user-header">
                <img src="~/Content/img/user-256.png" class="img-circle" alt="User Image" />
                <p>
                    <strong>@User.Identity.Name.ToUpper()</strong><br />
                    @if (User.Identity.GetUserId().Equals("1"))
                    {
                        <strong>Administrador  </strong>
                    }
                    else
                    {
                        <strong>Trabajador </strong>
                    }
                </p>
            </li>
            <!-- Menu Body -->
            <li class="user-body">
                <div class="row">

                </div>
                <!-- /.row -->
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
                @*<div class="pull-left">
                        <a href="#" class="btn btn-default btn-flat">Perfil</a>
                    </div>*@
                <div class="pull-right">
                    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                    {
                        @Html.AntiForgeryToken()
                        <a href="javascript:document.getElementById('logoutForm').submit()" class="btn btn-default btn-flat">Cerrar sesi&oacute;n</a>
                    }
                </div>
            </li>
        </ul>
    </li>
}

WebGestionPlanilla/Views/Shared/_LayoutMinimal.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <!-- Enable compatibility -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge;IE=10;IE=9" />
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <!-- Title of page -->
    <title>@ViewBag.Title</title>
    <!-- Icon application -->
    <link rel="icon" href="~/favicon.ico">
    <!-- Styles -->
    <link href="~/Content/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/lib/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet" />
    <link href="~/Content/css/main.css" rel="stylesheet" />
    <link href="~/Content/css/skin-red.css" rel="stylesheet" />
    <script src="~/Content/lib/modernizr/js/modernizr-2.8.3.js"></script>
</head>
<body class="skin-red">
    <!-- Layout -->
    <div class="bsp-wrapper">
        <!-- Body -->
        <div class="bsp-body-wrapper">
            <!-- Header -->
            <div class="bsp-header">
                <div class="container-fluid">
                    <span class="bsp-brand">
                        @*<img src="~/Content/img/full_logo_withe_transparent_2.png" alt="Logo" />*@
                    </span>
                </div>
            </div>
            <!-- Content -->
            <div class="bsp-content">
                <div class="container-fluid" id="bodyMainContent">
                    @RenderBody()
                </div>
            </div>
            <!-- Footer -->
            <div class="bsp-footer">
                <div class="container-fluid">
                    <footer>
                        @*@(string.Format("{0} | {1} {2}", AppConfig.ApplicationCopyright, AppConfig.ApplicationShortName, AppConfig.ApplicationVersion))*@
                    </footer>
                </div>
            </div>
        </div>
    </div>
    <!-- Scripts -->
    <script src="~/Content/lib/jquery/js/jquery-3.3.1.min.js"></script>
    <script src="~/Content/lib/jquery/js/jquery.validate.min.js"></script>
    <script src="~/Content/lib/jquery/js/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Content/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Content/lib/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="~/Content/lib/bootstrap-datepicker/js/bootstrap-datepicker.es.min.js"></script>
    <script type="text/javascript">
            var baseSiteUrl = '@Url.Content("~/")';
    </script>
    <script src="~/Content/js/app.js"></script>
    @RenderSection("scripts", required: false)
</body>

</html>